const express = require('express');
const axios = require('axios');
const { google } = require('googleapis');
const app = express();
app.use(express.json());
const VERIFY_TOKEN=process.env.VERIFY_TOKEN||'dra-rosina-2024';
const WHATSAPP_TOKEN=process.env.WHATSAPP_TOKEN;
const PHONE_NUMBER_ID=process.env.PHONE_NUMBER_ID;
const ANTHROPIC_KEY=process.env.ANTHROPIC_API_KEY;
const CALENDAR_ID=process.env.GOOGLE_CALENDAR_ID;
const PORT=process.env.PORT||3000;
const GOOGLE_CREDS={type:'service_account',project_id:process.env.GOOGLE_PROJECT_ID,private_key_id:process.env.GOOGLE_PRIVATE_KEY_ID,private_key:(process.env.GOOGLE_PRIVATE_KEY||'').replace(/\\n/g,'\n'),client_email:process.env.GOOGLE_CLIENT_EMAIL,client_id:process.env.GOOGLE_CLIENT_ID,token_uri:'https://oauth2.googleapis.com/token'};
const clientes={};
const SERVICIOS=['Botox / Toxina botulinica','Rellenos de acido hialuronico','Limpieza facial','Tratamientos laser','Mesoterapia'];
const REL={'Botox / Toxina botulinica':['Rellenos de acido hialuronico','Mesoterapia'],'Rellenos de acido hialuronico':['Botox / Toxina botulinica','Tratamientos laser'],'Limpieza facial':['Mesoterapia','Tratamientos laser'],'Tratamientos laser':['Limpieza facial','Mesoterapia'],'Mesoterapia':['Botox / Toxina botulinica','Limpieza facial']};
const SYS='Eres Bon, ayudante personal de Mely (Dra. Rosina). Responde en espanol de Mexico, tono calido y cercano. Max 3 oraciones. Nunca digas que eres IA o bot. Usa el historial del cliente.';
async function getCal(){const auth=new google.auth.GoogleAuth({credentials:GOOGLE_CREDS,scopes:['https://www.googleapis.com/auth/calendar']});return google.calendar({version:'v3',auth});}
async function getSlots(fecha){const B={1:['10:00','11:00','13:00','16:00'],2:['09:00','11:30','15:00','17:00'],3:['10:00','12:00','14:30'],4:['09:30','11:00','16:00','17:30'],5:['10:00','13:00','15:00']};try{const c=await getCal();const r=await c.events.list({calendarId:CALENDAR_ID,timeMin:new Date(fecha+'T00:00:00').toISOString(),timeMax:new Date(fecha+'T23:59:59').toISOString(),singleEvents:true});const busy=(r.data.items||[]).map(e=>{const d=new Date(e.start.dateTime||e.start.date);return String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0');});const dow=new Date(fecha+'T12:00:00').getDay();return(B[dow]||[]).filter(s=>!busy.includes(s));}catch(e){const dow=new Date(fecha+'T12:00:00').getDay();return B[dow]||[];}}
async function crearEvento(c){try{const cal=await getCal();const[y,m,d]=c.fecha.split('-').map(Number);const[h,min]=c.hora.split(':').map(Number);const ini=new Date(y,m-1,d,h,min);await cal.events.insert({calendarId:CALENDAR_ID,resource:{summary:c.nombre+' - '+c.srv,description:'WA:'+c.phone,start:{dateTime:ini.toISOString(),timeZone:'America/Mexico_City'},end:{dateTime:new Date(ini.getTime()+3600000).toISOString(),timeZone:'America/Mexico_City'}}});}catch(e){console.error('cal:',e.message);}}
async function txt(to,text){try{await axios.post('https://graph.facebook.com/v18.0/'+PHONE_NUMBER_ID+'/messages',{messaging_product:'whatsapp',to,type:'text',text:{body:text}},{headers:{Authorization:'Bearer '+WHATSAPP_TOKEN,'Content-Type':'application/json'}});}catch(e){console.error('txt:',e.response?.data||e.message);}}
async function btn(to,body,opts){try{if(opts.length<=3){await axios.post('https://graph.facebook.com/v18.0/'+PHONE_NUMBER_ID+'/messages',{messaging_product:'whatsapp',to,type:'interactive',interactive:{type:'button',body:{text:body},action:{buttons:opts.map((o,i)=>({type:'reply',reply:{id:'o'+i,title:String(o).slice(0,20)}}))}}},{headers:{Authorization:'Bearer '+WHATSAPP_TOKEN,'Content-Type':'application/json'}});}else{await axios.post('https://graph.facebook.com/v18.0/'+PHONE_NUMBER_ID+'/messages',{messaging_product:'whatsapp',to,type:'interactive',interactive:{type:'list',body:{text:body},action:{button:'Ver opciones',sections:[{title:'Opciones',rows:opts.map((o,i)=>({id:'o'+i,title:String(o).slice(0,24)}))}]}}},{headers:{Authorization:'Bearer '+WHATSAPP_TOKEN,'Content-Type':'application/json'}});}}catch(e){await txt(to,body+'\n\n'+opts.map((o,i)=>(i+1)+'. '+o).join('\n'));}}
function getDias(mes,anio){const N=['Dom','Lun','Mar','Mie','Jue','Vie','Sab'];const hoy=new Date();hoy.setHours(0,0,0,0);const dias=[];const f=new Date(anio,mes-1,1);while(f.getMonth()===mes-1){const dow=f.getDay();if([1,2,3,4,5].includes(dow)&&f>hoy){const dd=f.getDate();dias.push({label:N[dow]+' '+dd,fecha:anio+'-'+String(mes).padStart(2,'0')+'-'+String(dd).padStart(2,'0')});}f.setDate(f.getDate()+1);}return dias;}
function fmt(fechaStr,hora){const[y,m,d]=fechaStr.split('-').map(Number);const f=new Date(y,m-1,d);const D=['domingo','lunes','martes','miercoles','jueves','viernes','sabado'];const M=['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'];const h=parseInt(hora);const ap=h>=12?'PM':'AM';const h12=h>12?h-12:h===0?12:h;return D[f.getDay()]+' '+d+' de '+M[m-1]+' de '+y+' a las '+h12+':'+hora.split(':')[1]+' '+ap;}
function detSrv(t){const s=t.toLowerCase();if(s.includes('botox')||s.includes('toxina'))return SERVICIOS[0];if(s.includes('relleno')||s.includes('hialur'))return SERVICIOS[1];if(s.includes('limpieza'))return SERVICIOS[2];if(s.includes('laser'))return SERVICIOS[3];if(s.includes('mesoterapia'))return SERVICIOS[4];return null;}
const E={I:'inicio',N:'nombre',S:'servicio',M:'mes',D:'dia',H:'hora',C:'confirmar',L:'libre'};
async function handle(phone,texto){
if(!clientes[phone])clientes[phone]={phone,nombre:null,estado:E.I,srv:null,ultimoSrv:null,hist:[],dias:[],fecha:null,hora:null,remSet:false,retSet:false};
const c=clientes[phone];const t=(texto||'').toLowerCase().trim();
if(c.estado===E.I){if(c.nombre){c.estado=E.S;await btn(phone,'Hola '+c.nombre+'! Que te gustaria hacer?',['Agendar cita','Ver servicios']);}else{c.estado=E.N;await txt(phone,'Hola! Soy Bon. Me dices tu nombre completo?');}return;}
if(c.estado===E.N){const m=texto.match(/\b(\w{2,})\s+(\w{2,})\b/);if(m){c.nombre=m[1]+' '+m[2];c.estado=E.S;await txt(phone,'Mucho gusto, '+c.nombre+'!');await btn(phone,'Servicios disponibles:',SERVICIOS.slice(0,3));await btn(phone,'Tambien tenemos:',SERVICIOS.slice(3));}else await txt(phone,'Necesito nombre y apellido completos.');return;}
if(c.estado===E.S){if(t.includes('agendar')||t.includes('cita')){await btn(phone,'Que servicio quieres?',SERVICIOS.slice(0,3));await btn(phone,'Tambien:',SERVICIOS.slice(3));return;}if(t.includes('servicios')){await btn(phone,'Estos son:',SERVICIOS.slice(0,3));await btn(phone,'Tambien:',SERVICIOS.slice(3));return;}const srv=detSrv(texto);if(srv){c.srv=srv;c.estado=E.M;const hoy=new Date();const ME=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];const meses=[0,1,2].map(i=>{const d2=new Date(hoy.getFullYear(),hoy.getMonth()+i,1);return ME[d2.getMonth()]+' '+d2.getFullYear();});await btn(phone,'En que mes quieres tu cita?',meses);}else{await btn(phone,'Cual te interesa?',SERVICIOS.slice(0,3));await btn(phone,'Tambien:',SERVICIOS.slice(3));}return;}
if(c.estado===E.M){const MM={enero:1,febrero:2,marzo:3,abril:4,mayo:5,junio:6,julio:7,agosto:8,septiembre:9,octubre:10,noviembre:11,diciembre:12};let mes=null,anio=new Date().getFullYear();Object.entries(MM).forEach(([n,v])=>{if(t.includes(n))mes=v;});const am=t.match(/\d{4}/);if(am)anio=parseInt(am[0]);if(mes){const dias=getDias(mes,anio).slice(0,9);c.dias=dias;if(!dias.length){await txt(phone,'No hay dias ese mes. Prueba otro.');return;}c.estado=E.D;await btn(phone,'Que dia te queda mejor?',dias.slice(0,3).map(d=>d.label));if(dias.length>3)await btn(phone,'O tambien:',dias.slice(3,6).map(d=>d.label));if(dias.length>6)await btn(phone,'O tambien:',dias.slice(6,9).map(d=>d.label));}else await txt(phone,'En que mes? Ej: Abril o Mayo.');return;}
if(c.estado===E.D){let dia=c.dias.find(d=>t.includes(d.label.toLowerCase()));if(!dia){const nm=t.match(/\b(\d{1,2})\b/);if(nm)dia=c.dias.find(d=>parseInt(d.label.split(' ')[1])===parseInt(nm[1]));}if(dia){c.fecha=dia.fecha;const slots=await getSlots(dia.fecha);if(!slots.length){await txt(phone,'Ese dia no tiene horarios. Otro?');return;}c.estado=E.H;await btn(phone,'A que hora el '+dia.label+'?',slots.slice(0,3));if(slots.length>3)await btn(phone,'O tambien:',slots.slice(3,6));}else await txt(phone,'No encontre ese dia. El numero? (ej: 14)');return;}
if(c.estado===E.H){const hm=texto.match(/\b(\d{1,2}:\d{2})\b/);if(hm){c.hora=hm[1];c.estado=E.C;const ff=fmt(c.fecha,c.hora);await btn(phone,'Confirma, '+c.nombre+':\n\n'+c.srv+'\n'+ff+'\n\nTodo correcto?',['Confirmar','Cambiar']);}else await txt(phone,'A que hora? Ej: 10:00');return;}
if(c.estado===E.C){if(t.includes('confirm')||t.includes('si')||t.includes('ok')||t.includes('dale')){const ff=fmt(c.fecha,c.hora);c.hist.push({srv:c.srv,fecha:c.fecha,hora:c.hora,ff});c.ultimoSrv=c.srv;await crearEvento(c);await txt(phone,'Cita confirmada, '+c.nombre+'!\n\n'+c.srv+'\n'+ff+'\n\nTe mando recordatorio 1 hora antes!');recs(phone);c.estado=E.L;}else if(t.includes('cambi')||t.includes('no')){c.estado=E.S;c.srv=null;c.fecha=null;c.hora=null;await btn(phone,'Sin problema. Que cambiamos?',['Servicio','Fecha y hora']);}return;}
if(c.estado===E.L){if(t.includes('cita')||t.includes('agendar')){c.estado=E.S;c.srv=null;await btn(phone,'Que servicio esta vez?',SERVICIOS.slice(0,3));await btn(phone,'Tambien:',SERVICIOS.slice(3));return;}try{const ctx=c.hist.length>0?'Ultima cita: '+c.ultimoSrv+' el '+c.hist[c.hist.length-1].ff+'.':'Sin citas previas.';const r=await axios.post('https://api.anthropic.com/v1/messages',{model:'claude-haiku-4-5-20251001',max_tokens:200,system:SYS+'\nCliente: '+c.nombre+'. '+ctx,messages:[{role:'user',content:texto}]},{headers:{'x-api-key':ANTHROPIC_KEY,'anthropic-version':'2023-06-01','Content-Type':'application/json'}});await txt(phone,r.data.content.map(b=>b.text||'').join(''));}catch(e){await txt(phone,'Hola '+c.nombre+'! Necesitas algo?');}return;}
c.estado=E.I;await handle(phone,texto);}
function recs(phone){const c=clientes[phone];if(!c||c.remSet)return;c.remSet=true;const p=process.env.NODE_ENV!=='production';setTimeout(async()=>{const u=c.hist[c.hist.length-1];await txt(phone,'Recordatorio: Hola '+c.nombre+'! Tu cita es en 1 hora:\n'+u?.srv+'\n'+u?.ff+'\n\nNos vemos!');},p?60000:3600000);setTimeout(async()=>{if(c.retSet)return;c.retSet=true;const rel=(REL[c.ultimoSrv]||[]).map(s=>'- '+s).join('\n');await txt(phone,'Hola '+c.nombre+'! Han pasado 5 meses desde tu '+c.ultimoSrv+'. Tiempo de retoque!\n\nTambien tenemos:\n'+rel+'\n\nTe agendo?');c.estado=E.S;},p?300000:13140000000);}
app.get('/webhook',(req,res)=>{if(req.query['hub.mode']==='subscribe'&&req.query['hub.verify_token']===VERIFY_TOKEN)res.status(200).send(req.query['hub.challenge']);else res.sendStatus(403);});
app.post('/webhook',async(req,res)=>{res.sendStatus(200);try{const msg=req.body?.entry?.[0]?.changes?.[0]?.value?.messages?.[0];if(!msg)return;const phone=msg.from;let texto=null;if(msg.type==='text')texto=msg.text?.body;else if(msg.type==='interactive')texto=msg.interactive?.button_reply?.title||msg.interactive?.list_reply?.title;if(!texto)return;await handle(phone,texto);}catch(e){console.error('wh:',e.message);}});
app.get('/',(req,res)=>res.json({status:'ok',bot:'Bon'}));
app.listen(PORT,()=>console.log('Bon en puerto '+PORT));